config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users

  get 'insta_sessions/connect'
  get 'insta_sessions/callback'

  get 'static/about_nicole'

  resources :posts do
    resources :comments, except: [:index, :show]
  end

  namespace :api do
    namespace :v1 do
      resources :posts, except: [:new, :edit]
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :content
  validates_presence_of :user_id
  validates_presence_of :post_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :blog_image, BlogImageUploader
  has_many :comments, dependent: :destroy

  validates_presence_of :subject
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController

  def index
    render json: Post.all
  end

  def show
    render json: Post.find(params[:id])
  end

  def create
    @uploader.store!(params[:blog_image])
    @post = Post.new(post_params)
    if @post.save
    else
      render json: { errors: @post.errors }, status: 422
    end
  end

  def update
    @uploader.store!(params[:blog_image])
    if @post.update(post_params)
    else
      render json: { errors: @post.errors }, status: 422
    end
  end

  def destroy
    @post.destroy
  end

  private

  def post_params
    params.require(:post).permit(:content, :subject, :blog_image, :instagram_link)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  def authenticate
    unless is_nicole?
      redirect_to posts_path, alert: "You are not authorized, this is Nicole's Blog!"
    end
  end

  def authorize
    unless current_user
      redirect_to posts_path, alert: "Please sign in to comment."
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize
  before_action :get_post

  def get_post
    @post = Post.find(params[:post_id])
  end

  def new
    @comment = Comment.new(post: @post)
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @post, notice: "Comment posted."
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    unless current_user == @comment.user
      redirect_to @post, notice: "You are not authorized!"
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @post, notice: "Comment Edited"
    else
      render :update
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to @post, notice: "Comment Deleted"
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :content)
  end
end

app/controllers/insta_sessions_controller.rb
class InstaSessionsController < ApplicationController
  def connect
    redirect_to Instagram.authorize_url(redirect_uri: ENV['CALLBACK_URL'])
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => ENV['CALLBACK_URL'])
    session[:access_token] = response.access_token
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, only: [:new, :create, :edit, :update]
  before_action :get_post, except: [:new, :create, :index]
  before_action :get_uploader, only: [:update, :create, :index, :show]

  def get_post
    @post = Post.find(params[:id])
  end

  def get_uploader
    @uploader = BlogImageUploader.new
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @client = Instagram.client(access_token: session[:access_token])
    @post = Post.new
  end

  def create
    @uploader.store!(params[:blog_image])
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "You posted!"
    else
      render :new
    end
  end

  def edit
    @client = Instagram.client(access_token: session[:access_token])
  end

  def update
    @uploader.store!(params[:blog_image])
    if @post.update(post_params)
      redirect_to @post, notice: "Post updated"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post deleted"
  end

  private

  def post_params
    params.require(:post).permit(:content, :subject, :blog_image, :instagram_link)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about_nicole
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_nicole?
    if current_user && current_user.email == "nfelch121394@gmail.com"
       return true
    end
      false
  end
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end

  def nicolify(content)
    content = emojify(content)

    #code blocks
    content = h(content).to_str.gsub(/```([\s\S]*)```/) do |match|
      %(<code>#{$1}</code>)
    end.html_safe if content.present?

    #new lines
    content = h(content).to_str.gsub(/\n/) do |match|
      %(<br>)
    end.html_safe if content.present?

    #bold
    content = h(content).to_str.gsub(/\*([\s\S]*)\*/) do |match|
      %(<b>#{$1}</b>)
    end.html_safe if content.present?

    #italic
    content = h(content).to_str.gsub(/_([\s\S]*)_/) do |match|
      %(<i>#{$1}</i>)
    end.html_safe if content.present?
  end
end

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @comment] do |f| %>
  <%= f.input :content %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit "Post Comment", class: "button" %>
<% end %>

app/views/comments/edit.html.erb
<div class="row">
  <div class="columns small-12">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="row">
  <div class="columns small-12">
    <%= simple_form_for [@post, @comment] do |f| %>
      <%= f.input :content %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <%= f.submit "Post Comment", class: "button" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Blog</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% if is_nicole? %>
            <li><%= link_to 'New Post', new_post_path %></li>
            <% if !session[:access_token] %>
              <li><%= link_to 'InstaSignIn', insta_sessions_connect_path %></li>
            <% end %>
          <% end %>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
        <li><%= link_to 'About Me', static_about_nicole_path %></li>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <% if key == "notice" %>
    <div class="alert-box success" data-alert>
      <%= value %>
    </div>
    <% else %>
    <div class="alert-box alert" data-alert>
      <%= value %>
    </div>
    <% end %>
  <%- end -%>

  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :subject %>
  <%= f.input :content %>
  <%= f.input :blog_image, as: :file %>
  <%= f.input :instagram_link %>
  <button class="tiny success" data-reveal-id="myModal">Add...</button></br>

  <div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <a class="close-reveal-modal" aria-label="Close">X</a>
    <% @client.user_recent_media.each do |item| %>
      <img src="<%= item.images.thumbnail.url %>" id="<%= item.link %>" class="instagram" />
    <% end %>
  </div>
  <%= f.submit "Post!", class: "button" %>
<% end %>

app/views/posts/_post.html.erb
<%= link_to post_path(post) do %>
  <div class="panel">
    <h1><%= nicolify(post.subject) %></h1>
    <% if post.blog_image %>
      <%= image_tag post.blog_image_url, class: "img" %>
    <% end %>
    <% if post.instagram_link.length > 0 %>
      <%= (Instagram.oembed(post.instagram_link).html).html_safe %>
    <% end %>
    <p><%= nicolify(post.content) %></p>
    <%= link_to "Leave a comment", new_post_comment_path(post) %>
    <% if is_nicole? %>
      | <%= link_to "Edit", edit_post_path(post) %>
      | <%= link_to "Delete Post", post_path(post), method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <div class="columns small-12">
    <div id="posts">
      <%= render @posts %>
    </div>

    <div id="infinite-scrolling">
      <%= foundation_paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/index.js.erb
$('#posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j foundation_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="columns small-12">
    <%= simple_form_for @post do |f| %>
      <%= f.input :subject %>
      <%= f.input :content %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="columns small-12">
    <%= render @post %>
    <% @post.comments.each do |c| %>
      <div class="callout panel">
        <p><%= emojify(c.content) %></p>
        - <%= c.user.email %>
        <% if current_user && c.user == current_user %>
          | <%= link_to "Edit Comment", edit_post_comment_path(@post, c) %>
          | <%= link_to "Delete Comment", post_comment_path(@post, c), method: :delete %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>